services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: studylog_app
      POSTGRES_USER: studylog_app
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      

volumes:
  pgdata:
