default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'studylog_app' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: studylog_app
  host: localhost

test:
  <<: *default
  database: myapp_test
  host: localhost

production:
  <<: *default
  database: myapp_production
  username: studylog_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: localhost